package com.saasapp.domain.models.auth;

/**
 * Supported two-factor authentication methods.
 */
public enum TwoFactorMethodType {
    /**
     * Code sent to the user's email address.
     */
    EMAIL,
    /**
     * Code sent via SMS to the user's phone number.
     */
    SMS,
    /**
     * Time-based one-time password generated by an authenticator app.
     */
    TOTP
}
