--liquibase formatted sql
--changeset saliou673:00006-app-configuration-create-table

CREATE TABLE IF NOT EXISTS app_configuration
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    category         VARCHAR(50)  NOT NULL,
    code             VARCHAR(50)  NOT NULL,
    label            VARCHAR(255) NOT NULL,
    description      TEXT,
    active           BOOLEAN      NOT NULL DEFAULT TRUE,
    creation_date    TIMESTAMP    NOT NULL,
    last_update_date TIMESTAMP    NOT NULL,
    last_updated_by  TEXT         NOT NULL,
    CONSTRAINT pk_app_configuration PRIMARY KEY (id),
    CONSTRAINT un_app_configuration_category_code UNIQUE (category, code)
);
