--liquibase formatted sql
--changeset saliou673:00016-security-settings-create-table

CREATE TABLE IF NOT EXISTS app_security_settings
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    two_factor_required  BOOLEAN      NOT NULL DEFAULT FALSE,
    creation_date        TIMESTAMP    NOT NULL,
    last_update_date     TIMESTAMP    NOT NULL,
    last_updated_by      TEXT         NOT NULL,
    CONSTRAINT pk_app_security_settings PRIMARY KEY (id)
);
