--liquibase formatted sql
--changeset saliou673:00001-app-user-create-table

CREATE TABLE IF NOT EXISTS app_user
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    email                  TEXT         NOT NULL,
    phone_number           VARCHAR(20),
    password_hash          TEXT,
    first_name             VARCHAR(255) NOT NULL,
    last_name              VARCHAR(50)  NOT NULL,
    birth_date             DATE,
    gender                 VARCHAR(6),
    address                VARCHAR(255),
    status                 VARCHAR(25)  NOT NULL,
    activation_date        TIMESTAMP,
    activation_code        TEXT,
    reset_code             TEXT,
    reset_date             TIMESTAMP,
    language_key           TEXT,
    two_factor_enabled     BOOLEAN      NOT NULL DEFAULT FALSE,
    two_factor_method      VARCHAR(50),
    totp_secret            TEXT,
    pending_email          TEXT,
    email_change_code      TEXT,
    email_change_code_date TIMESTAMP,
    image_url              TEXT,
    creation_date          TIMESTAMP    NOT NULL,
    last_update_date       TIMESTAMP    NOT NULL,
    last_updated_by        TEXT         NOT NULL,

    CONSTRAINT pk_app_user PRIMARY KEY (id),
    CONSTRAINT un_app_user_email UNIQUE (email),
    CONSTRAINT un_app_user_phone_number UNIQUE (phone_number),
    CONSTRAINT un_app_user_activation_code UNIQUE (activation_code),
    CONSTRAINT un_app_user_reset_code UNIQUE (reset_code),
    CONSTRAINT un_app_user_email_change_code UNIQUE (email_change_code),
    CONSTRAINT un_app_user_pending_email UNIQUE (pending_email)
);