--liquibase formatted sql
--changeset saliou673:00005-refresh-token-create-table

CREATE TABLE IF NOT EXISTS auth_token
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    refresh_token TEXT                     NOT NULL,
    access_token  TEXT                     NOT NULL,
    remember_me   BOOLEAN                  NOT NULL,
    expiry_date   TIMESTAMP WITH TIME ZONE NOT NULL,
    user_id       BIGINT,
    creation_date TIMESTAMP                NOT NULL,
    CONSTRAINT pk_auth_token PRIMARY KEY (id),
    CONSTRAINT fk_auth_token_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE,
    CONSTRAINT un_auth_token_user_id_token UNIQUE (user_id, refresh_token)
);

CREATE INDEX IF NOT EXISTS idx_auth_token_value ON auth_token (refresh_token);
CREATE INDEX IF NOT EXISTS idx_auth_token_user_id ON auth_token (user_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_auth_token_access_token ON auth_token (access_token);